env:
  browser: true
  es2021: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - "@typescript-eslint"

settings:
  import/extensions:
    - ".js"
    - ".jsx"
    - ".ts"
    - ".tsx"
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"

rules:
  "no-console": "error"
  "import/extensions": 0
  "no-param-reassign": 0
  "object-curly-newline": 0
  "semi": ["error", "always"]
  "function-paren-newline": 0
  "implicit-arrow-linebreak": 0
  "import/prefer-default-export": 0
  "@typescript-eslint/no-explicit-any": 0
  "import/order": [ "error", {
    "groups": [ "builtin", "external", "internal", "parent", "sibling", "index", "object", "type" ],
    "newlines-between": "always",
  }]
  "comma-dangle": ["error", {
    "functions": "only-multiline",
    "objects": "only-multiline",
    "arrays": "only-multiline",
  }]
  "@typescript-eslint/no-unused-vars": ["error"]
  "@typescript-eslint/no-empty-interface": ["error"]
  "@typescript-eslint/ban-ts-comment": ["error"]

