env:
  browser: true
  es2021: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - "@typescript-eslint"

settings:
  import/extensions:
    - ".js"
    - ".jsx"
    - ".ts"
    - ".tsx"
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"

rules:
  "no-console": "error",
  "semi": ["error", "always"],
  "import/order": [ "error", {
    "groups": [ "builtin", "external", "internal", "parent", "sibling", "index", "object", "type" ],
    "newlines-between": "always",
  }]
  "comma-dangle": ["error", {
    "functions": "only-multiline",
    "objects": "only-multiline",
    "arrays": "only-multiline",
  }]
